Models/ErrorViewModel.cs
namespace WRproyectoCompleto.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WRproyectoCompleto.Models;

namespace WRproyectoCompleto.Controllers;

public class HomeController : Controller
{

    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/WREstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WRproyectoCompleto.Data;
using WRproyectoCompleto.Models;

namespace WRproyectoCompleto.Controllers
{
    public class WREstudianteController : Controller
    {
        private readonly WRproyectoCompletoContext _context;

        public WREstudianteController(WRproyectoCompletoContext context)
        {
            _context = context;
        }

        // GET: WREstudiante
        public async Task<IActionResult> Index()
        {
            return View(await _context.WREstudiante.ToListAsync());
        }

        // GET: WREstudiante/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wREstudiante = await _context.WREstudiante
                .FirstOrDefaultAsync(m => m.WRestudianteId == id);
            if (wREstudiante == null)
            {
                return NotFound();
            }

            return View(wREstudiante);
        }

        // GET: WREstudiante/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WREstudiante/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WRestudianteId,WRcedulaEstudiante,WRnombreEstudiante,WRapellidoEstudiante,WRnombreRepresentanteEstudiante,WRedad")] WREstudiante wREstudiante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(wREstudiante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(wREstudiante);
        }

        // GET: WREstudiante/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wREstudiante = await _context.WREstudiante.FindAsync(id);
            if (wREstudiante == null)
            {
                return NotFound();
            }
            return View(wREstudiante);
        }

        // POST: WREstudiante/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WRestudianteId,WRcedulaEstudiante,WRnombreEstudiante,WRapellidoEstudiante,WRnombreRepresentanteEstudiante,WRedad")] WREstudiante wREstudiante)
        {
            if (id != wREstudiante.WRestudianteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(wREstudiante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WREstudianteExists(wREstudiante.WRestudianteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(wREstudiante);
        }

        // GET: WREstudiante/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wREstudiante = await _context.WREstudiante
                .FirstOrDefaultAsync(m => m.WRestudianteId == id);
            if (wREstudiante == null)
            {
                return NotFound();
            }

            return View(wREstudiante);
        }

        // POST: WREstudiante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var wREstudiante = await _context.WREstudiante.FindAsync(id);
            if (wREstudiante != null)
            {
                _context.WREstudiante.Remove(wREstudiante);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WREstudianteExists(int id)
        {
            return _context.WREstudiante.Any(e => e.WRestudianteId == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Solucion Completa</h1>
    <h2 class="display-5">William Ramirez</h2>
    <p>Solucion Completa para programación IV.</p>
    <p>Esta es la aplicación Web MVC.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WRproyectoCompleto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WRproyectoCompleto.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WRproyectoCompleto</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="WREstudiante">WREstudiantes</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - WRproyectoCompleto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/WREstudiante/Create.cshtml
@model WRproyectoCompleto.Models.WREstudiante

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>WREstudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WRcedulaEstudiante" class="control-label"></label>
                <input asp-for="WRcedulaEstudiante" class="form-control" />
                <span asp-validation-for="WRcedulaEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WRnombreEstudiante" class="control-label"></label>
                <input asp-for="WRnombreEstudiante" class="form-control" />
                <span asp-validation-for="WRnombreEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WRapellidoEstudiante" class="control-label"></label>
                <input asp-for="WRapellidoEstudiante" class="form-control" />
                <span asp-validation-for="WRapellidoEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WRnombreRepresentanteEstudiante" class="control-label"></label>
                <input asp-for="WRnombreRepresentanteEstudiante" class="form-control" />
                <span asp-validation-for="WRnombreRepresentanteEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WRedad" class="control-label"></label>
                <input asp-for="WRedad" class="form-control" />
                <span asp-validation-for="WRedad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/WREstudiante/Delete.cshtml
@model WRproyectoCompleto.Models.WREstudiante

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WREstudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRcedulaEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRcedulaEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRnombreEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRnombreEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRapellidoEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRapellidoEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRnombreRepresentanteEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRnombreRepresentanteEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRedad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRedad)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="WRestudianteId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/WREstudiante/Details.cshtml
@model WRproyectoCompleto.Models.WREstudiante

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>WREstudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRcedulaEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRcedulaEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRnombreEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRnombreEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRapellidoEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRapellidoEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRnombreRepresentanteEstudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRnombreRepresentanteEstudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WRedad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WRedad)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.WRestudianteId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/WREstudiante/Edit.cshtml
@model WRproyectoCompleto.Models.WREstudiante

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>WREstudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="WRestudianteId" />
            <div class="form-group">
                <label asp-for="WRcedulaEstudiante" class="control-label"></label>
                <input asp-for="WRcedulaEstudiante" class="form-control" />
                <span asp-validation-for="WRcedulaEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WRnombreEstudiante" class="control-label"></label>
                <input asp-for="WRnombreEstudiante" class="form-control" />
                <span asp-validation-for="WRnombreEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WRapellidoEstudiante" class="control-label"></label>
                <input asp-for="WRapellidoEstudiante" class="form-control" />
                <span asp-validation-for="WRapellidoEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WRnombreRepresentanteEstudiante" class="control-label"></label>
                <input asp-for="WRnombreRepresentanteEstudiante" class="form-control" />
                <span asp-validation-for="WRnombreRepresentanteEstudiante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WRedad" class="control-label"></label>
                <input asp-for="WRedad" class="form-control" />
                <span asp-validation-for="WRedad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/WREstudiante/Index.cshtml
@model IEnumerable<WRproyectoCompleto.Models.WREstudiante>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.WRcedulaEstudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WRnombreEstudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WRapellidoEstudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WRnombreRepresentanteEstudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WRedad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.WRcedulaEstudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WRnombreEstudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WRapellidoEstudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WRnombreRepresentanteEstudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WRedad)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.WRestudianteId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.WRestudianteId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.WRestudianteId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>